image: docker:19.03.11

services:
  - docker:19.03.11-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  HV_REF_POINT: "[1, 1]"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

test-build-best:
  stage: test
  script:
    - cd example/best
    - docker build --tag best:latest .
    - 'echo -e "{\"objective\": 1}\n[{\"score\": 3}, {\"score\": 2}]" | docker run -i best:latest'
    - 'echo -e "{\"objective\": 2}\n[{\"score\": 3}, {\"score\": 1}]" | docker run -i best:latest'

test-build-hypervolume:
  stage: test
  script:
    - cd example/hypervolume
    - docker build --tag hypervolume:latest .
    - 'echo -e "{\"objective\": [1, 0]}\n[{\"objective\": [0, 1]}, {\"objective\": [0.5, 0.5]}]" | docker run -i --env HV_REF_POINT hypervolume:latest'
    - 'echo -e "{\"objective\": [1, 0]}\n[{\"objective\": [0, 1]}, {\"objective\": [0.5, 0.5]}]" | docker run -i hypervolume:latest'

test-best:
  stage: test
  image: python:3.6
  before_script:
    - cd example/best
  script:
    - 'echo -e "{\"objective\": 1}\n[{\"score\": 3}, {\"score\": 2}]" | python best.py'
    - 'echo -e "{\"objective\": 2}\n[{\"score\": 3}, {\"score\": 1}]" | python best.py'

test-hypervolume:
  stage: test
  image: mikebentley15/pagmo2:2.11.3
  before_script:
    - cd example/hypervolume
  script:
    - 'echo -e "{\"objective\": [1, 0]}\n[{\"objective\": [0, 1]}, {\"objective\": [0.5, 0.5]}]" | python3 hv.py'
